---
 files: 
   - name: "vcf"
     output: "results/deepsomatic_run_deepsomatic/{sample}.include.panel.vcf.gz"
     input: "variant_calling/deepsomatic_run_deepsomatic/{sample}.include.panel.vcf.gz"
   - name: "sv_vcf"
     output: "results/pbsv_call_structural_variants/{sample}.include.panel.vcf.gz"
     input: "variant_calling/pbsv_call_structural_variants/{sample}.include.panel.vcf.gz"
  
