---
output: "../../config/output_files.yaml"
resources: "config/resources.yaml"
samples: "config/samples.tsv"
units: "config/units.tsv"

reference:
  fasta: "ref_data/genome.fasta"
  fai: "ref_data/genome.fasta.fai"
  trf: "ref_data/human_trf.bed"
  design_bed: "ref_data/test_genes.bed"
  targets_bed: "ref_data/test_genes.bed"

deepsomatic_t_only:
  pon: "ref_data/bcftools_merge/normal_db.vcf"

cnvkit_batch:
  normal_reference: "ref_data/cnvkit_build_normal_reference/cnvkit.PoN.cnn"

bcftools_filter_include_region:
  panel: "ref_data/test_genes.bed"

pbsv_discover:
  trf: "ref_data/human_trf.bed"

hificnv:
  exclude: "ref_data/cnv_excluded_regions.bed"

general_report: "../../config/report.yaml"