---
output: "../../config/output_files.yaml"
resources: "config/resources.yaml"
samples: "config/samples.tsv"
units: "config/units.tsv"

reference:
  fasta: "ref_data/genome.fasta"
  fai: "ref_data/genome.fasta.fai"
  trf: "ref_data/human_trf.bed"
  design_bed: "ref_data/test_genes.bed"
  targets_bed: "ref_data/test_genes.bed"

cnvkit_batch:
  normal_reference: "ref_data/cnvkit_build_normal_reference/cnvkit.PoN.cnn"

bcftools_filter_include_region:
  panel: "ref_data/test_genes.bed"

pbsv_discover:
  trf: "ref_data/human_trf.bed"

general_report: "../../config/report.yaml"

vep:
  vep_cache: "ref_data/VEP"

filter_vcf:
  germline: "../../config/filters/config_hard_filter_germline_vep.yaml"

merge_cnv_json:
  annotations:
   - "ref_data/myeloma_annotated_genes_only.bed"
