idid_min_len: 1000
snvs_keep:
  - "intergenic_variant"
  - "missense_variant"
  - "upstream_gene_variant"
format_fields:
  - "GT"
  - "GQ"
  - "DP"
  - "AD"
  - "AF"
  - "PL"
columns_keep:
  - "CHROM"
  - "POS"
  - "REF"
  - "ALT"
  - "QUAL"
  - "FILTER"
  - "Consequence"
  - "IMPACT"
  - "SYMBOL"
  - "Feature_type"
  - "BIOTYPE"
  - "EXON"
  - "INTRON"
  - "cDNA_position"
  - "CDS_position"
  - "Protein_position"
  - "Amino_acids"
  - "Codons"
  - "Existing_variation"
  - "gnomADe_AF"
  - "VARIANT_CLASS"
  - "SOMATIC"
  - "PHENO"
  - "AF"
  - "GT"
  - "GQ"
  - "DP"
  - "AD"
# NOT USED ANYMORE
columns_readable_names:
  - "CHROM"
  - "POS"
  - "REF"
  - "ALT"
  - "QUAL"
  - "FILTER"
  - "Consequence"
  - "IMPACT"
  - "GENE"
  - "FEATURE"
  - "TYPE"
  - "EXON"
  - "INTRON"
  - "KNOWN_VARIATION"
  - "VARIANT_CLASS"
  - "AF"
  - "GT"
  - "GQ"
  - "DP"
  - "AD"
vep_info_fields:
  - "Allele"
  - "Consequence"
  - "IMPACT"
  - "SYMBOL"
  - "Gene"
  - "Feature_type"
  - "Feature"
  - "BIOTYPE"
  - "EXON"
  - "INTRON"
  - "HGVSc"
  - "HGVSp"
  - "cDNA_position"
  - "CDS_position"
  - "Protein_position"
  - "Amino_acids"
  - "Codons"
  - "Existing_variation"
  - "DISTANCE"
  - "STRAND"
  - "FLAGS"
  - "VARIANT_CLASS"
  - "SYMBOL_SOURCE"
  - "HGNC_ID"
  - "AF"
  - "gnomADe_AF"
  - "gnomADe_AFR_AF"
  - "gnomADe_AMR_AF"
  - "gnomADe_ASJ_AF"
  - "gnomADe_EAS_AF"
  - "gnomADe_FIN_AF"
  - "gnomADe_MID_AF"
  - "gnomADe_NFE_AF"
  - "gnomADe_REMAINING_AF"
  - "gnomADe_SAS_AF"
  - "CLIN_SIG"
  - "SOMATIC"
  - "PHENO"
