idid_min_len: 1000
snvs_remove:
  - "intergenic_variant"
  - "NMD_transcript_variant"
  - "non_coding_transcript_variant"
  - "upstream_gene_variant"
  - "downstream_gene_variant"
  - "TFBS_ablation"
  - "TFBS_amplification"
  - "TF_binding_site_variant"
  - "regulatory_region_ablation"
  - "regulatory_region_amplification"
  - "regulatory_region_variant"
format_fields:
  - "GT"
  - "GQ"
  - "DP"
  - "AD"
  - "AF"
  - "PL"
columns_keep:
  - "CHROM"
  - "POS"
  - "REF"
  - "ALT"
  - "QUAL"
  - "FILTER"
  - "Consequence"
  - "SYMBOL"
  - "EXON"
  - "INTRON"
  - "cDNA_position"
  - "CDS_position"
  - "Protein_position"
  - "Amino_acids"
  - "Codons"
  - "Existing_variation"
  - "gnomADe_AF"
  - "VARIANT_CLASS"
  - "SOMATIC"
  - "PHENO"
  - "AF"
  - "GT"
  - "GQ"
  - "DP"
  - "AD"
vep_info_fields:
  - "Allele"
  - "Consequence"
  - "IMPACT"
  - "SYMBOL"
  - "Gene"
  - "Feature_type"
  - "Feature"
  - "BIOTYPE"
  - "EXON"
  - "INTRON"
  - "HGVSc"
  - "HGVSp"
  - "cDNA_position"
  - "CDS_position"
  - "Protein_position"
  - "Amino_acids"
  - "Codons"
  - "Existing_variation"
  - "DISTANCE"
  - "STRAND"
  - "FLAGS"
  - "VARIANT_CLASS"
  - "SYMBOL_SOURCE"
  - "HGNC_ID"
  - "AF"
  - "gnomADe_AF"
  - "gnomADe_AFR_AF"
  - "gnomADe_AMR_AF"
  - "gnomADe_ASJ_AF"
  - "gnomADe_EAS_AF"
  - "gnomADe_FIN_AF"
  - "gnomADe_MID_AF"
  - "gnomADe_NFE_AF"
  - "gnomADe_REMAINING_AF"
  - "gnomADe_SAS_AF"
  - "CLIN_SIG"
